# Generated by Django 4.2.1 on 2023-05-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ordering', models.IntegerField()),
                ('published', models.BooleanField(default=True)),
                ('thumb', models.TextField()),
                ('title', models.TextField()),
                ('alias', models.TextField()),
                ('metadesc', models.TextField()),
                ('metakey', models.TextField()),
                ('schemamarkup', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avata', models.TextField()),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('paymentid', models.IntegerField()),
                ('paymentdate', models.DateField()),
                ('note', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeshop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('thumb', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('title', models.TextField()),
                ('alias', models.TextField()),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TranSactStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TinDang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('shortcontent', models.TextField()),
                ('content', models.TextField()),
                ('thumb', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('alias', models.TextField()),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('ishot', models.BooleanField(default=True)),
                ('isnewfeed', models.BooleanField(default=True)),
                ('views', models.IntegerField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakeshop.accounts')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakeshop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortdesc', models.TextField()),
                ('description', models.TextField()),
                ('price', models.FloatField(default=100.0)),
                ('discount', models.IntegerField()),
                ('thumb', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
                ('bestseller', models.BooleanField(default=True)),
                ('homeflag', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('tags', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('alias', models.TextField()),
                ('metadesc', models.TextField()),
                ('metakey', models.TextField()),
                ('unitslnstock', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakeshop.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField(default=100.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeshop.order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeshop.products')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tranSactStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakeshop.transactstatus'),
        ),
        migrations.CreateModel(
            name='AttributesPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=100.0)),
                ('active', models.BooleanField(default=True)),
                ('attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeshop.attributes')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeshop.products')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakeshop.roles'),
        ),
    ]
