# Generated by Django 4.2.1 on 2023-05-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0002_alter_order_paymentdate_alter_order_paymentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='ordernumber',
        ),
    ]
