# Generated by Django 4.2.1 on 2023-05-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0003_remove_orderdetail_ordernumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='total',
            new_name='sub_total',
        ),
    ]
